language: java
jdk:
- oraclejdk8
deploy:
  provider: openshift
  user: denis@devtty.de
  password:
    secure: MceyIz+1+TMFrFb248PzP40F2WM8vefO2xMqD9331OU5OV/r0Eh3jq5BY3BJyRiUyWQG/ZOa1eiRM/RI4VWelLnXZD3RF270eEd9xQZC/vu5mjaxbRRph73MYb7so9yUah1I7hVwCx44evQb302Vs6xk0y2KfFSvH2Kz5cvoLufMCrXZ+vXdE8h+zf0NvSEjpEDMNndYqyPbUR+9yE/duVC1OTV3U/n49p/KPkL1uqL3n0OFPfTMGoOItqOGCb3v89J3WEr4v/tZ5q5up7In0srYYEeDbL8hRJbO/TozVs2zheZq3SZW4T2RrtC0uwwzwim2aVLN47uo2UpTD7XzrfEevWGTAALBW/FnPoqz60VuO+1MSa5GyeKnPMCPsbBJrsuQ4JyVlIhya2BTXOEq2+IMOTlfDZGlYVhiO1pu64wmSkcf/Lgeqd2oG2BMFd6roJsh8rpAJz3f7v8IgdGZ2yhr9oTJ2AUPr0529Eaxx4EmKq788Gn7ciEnSZqSRi6+Ekr68l79pAV04tJ1PNvTiNNwE8qASXqFR3imNHn1n+5h2YQUdMDh4ECJEwjjoQ0ubSvDbgnSZysospc84CP3SQ5eSHTOKDXi0IETdixqPSgrSdBfHimYGbhhxsJFjMBocF2rP0Hxa78o2CDwgQz2741w6dRNoiQIPoGM41hpk88=
  app: neb27k
  domain: devtty
  on:
    repo: devtty/neb27
  skip_cleanup: true
before_install:
  - openssl aes-256-cbc -K $encrypted_6c24f35a0a4d_key -iv $encrypted_6c24f35a0a4d_iv
    -in src/main/resources/twitter4j.properties.enc -out src/main/resources/twitter4j.properties -d
before_deploy:
    - ls src/main/resources