//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{hafas_rest}JourneyDetailRef"/>
 *         &lt;element ref="{hafas_rest}Product" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}Notes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{hafas_rest}attlist.Departure"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "journeyDetailRef",
    "product",
    "notes"
})
@XmlRootElement(name = "Departure")
public class Departure {

    @XmlElement(name = "JourneyDetailRef", required = true)
    protected JourneyDetailRef journeyDetailRef;
    @XmlElement(name = "Product")
    protected Product product;
    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlAttribute(name = "name", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String name;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "stop", required = true)
    protected String stop;
    @XmlAttribute(name = "stopid", required = true)
    protected String stopid;
    @XmlAttribute(name = "stopExtId")
    protected String stopExtId;
    @XmlAttribute(name = "prognosisType")
    protected PrognosisType prognosisType;
    @XmlAttribute(name = "time", required = true)
    protected String time;
    @XmlAttribute(name = "date", required = true)
    protected String date;
    @XmlAttribute(name = "tz")
    protected Integer tz;
    @XmlAttribute(name = "track")
    protected String track;
    @XmlAttribute(name = "rtTime")
    protected String rtTime;
    @XmlAttribute(name = "rtDate")
    protected String rtDate;
    @XmlAttribute(name = "rtTz")
    protected Integer rtTz;
    @XmlAttribute(name = "rtTrack")
    protected String rtTrack;
    @XmlAttribute(name = "cancelled")
    protected Boolean cancelled;
    @XmlAttribute(name = "direction")
    protected String direction;
    @XmlAttribute(name = "timeAtArrival")
    protected String timeAtArrival;
    @XmlAttribute(name = "dateAtArrival")
    protected String dateAtArrival;
    @XmlAttribute(name = "rtTimeAtArrival")
    protected String rtTimeAtArrival;
    @XmlAttribute(name = "rtDateAtArrival")
    protected String rtDateAtArrival;
    @XmlAttribute(name = "trainNumber")
    protected String trainNumber;
    @XmlAttribute(name = "trainCategory")
    protected String trainCategory;
    @XmlAttribute(name = "isFastest")
    protected Boolean isFastest;

    /**
     * Gets the value of the journeyDetailRef property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyDetailRef }
     *     
     */
    public JourneyDetailRef getJourneyDetailRef() {
        return journeyDetailRef;
    }

    /**
     * Sets the value of the journeyDetailRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyDetailRef }
     *     
     */
    public void setJourneyDetailRef(JourneyDetailRef value) {
        this.journeyDetailRef = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setProduct(Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the stop property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStop() {
        return stop;
    }

    /**
     * Sets the value of the stop property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStop(String value) {
        this.stop = value;
    }

    /**
     * Gets the value of the stopid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopid() {
        return stopid;
    }

    /**
     * Sets the value of the stopid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopid(String value) {
        this.stopid = value;
    }

    /**
     * Gets the value of the stopExtId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopExtId() {
        return stopExtId;
    }

    /**
     * Sets the value of the stopExtId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopExtId(String value) {
        this.stopExtId = value;
    }

    /**
     * Gets the value of the prognosisType property.
     * 
     * @return
     *     possible object is
     *     {@link PrognosisType }
     *     
     */
    public PrognosisType getPrognosisType() {
        return prognosisType;
    }

    /**
     * Sets the value of the prognosisType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrognosisType }
     *     
     */
    public void setPrognosisType(PrognosisType value) {
        this.prognosisType = value;
    }

    /**
     * Gets the value of the time property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTime() {
        return time;
    }

    /**
     * Sets the value of the time property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTime(String value) {
        this.time = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDate(String value) {
        this.date = value;
    }

    /**
     * Gets the value of the tz property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getTz() {
        if (tz == null) {
            return  0;
        } else {
            return tz;
        }
    }

    /**
     * Sets the value of the tz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTz(Integer value) {
        this.tz = value;
    }

    /**
     * Gets the value of the track property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrack() {
        return track;
    }

    /**
     * Sets the value of the track property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrack(String value) {
        this.track = value;
    }

    /**
     * Gets the value of the rtTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtTime() {
        return rtTime;
    }

    /**
     * Sets the value of the rtTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtTime(String value) {
        this.rtTime = value;
    }

    /**
     * Gets the value of the rtDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtDate() {
        return rtDate;
    }

    /**
     * Sets the value of the rtDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtDate(String value) {
        this.rtDate = value;
    }

    /**
     * Gets the value of the rtTz property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getRtTz() {
        if (rtTz == null) {
            return  0;
        } else {
            return rtTz;
        }
    }

    /**
     * Sets the value of the rtTz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRtTz(Integer value) {
        this.rtTz = value;
    }

    /**
     * Gets the value of the rtTrack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtTrack() {
        return rtTrack;
    }

    /**
     * Sets the value of the rtTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtTrack(String value) {
        this.rtTrack = value;
    }

    /**
     * Gets the value of the cancelled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCancelled() {
        if (cancelled == null) {
            return false;
        } else {
            return cancelled;
        }
    }

    /**
     * Sets the value of the cancelled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCancelled(Boolean value) {
        this.cancelled = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the timeAtArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeAtArrival() {
        return timeAtArrival;
    }

    /**
     * Sets the value of the timeAtArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeAtArrival(String value) {
        this.timeAtArrival = value;
    }

    /**
     * Gets the value of the dateAtArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateAtArrival() {
        return dateAtArrival;
    }

    /**
     * Sets the value of the dateAtArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateAtArrival(String value) {
        this.dateAtArrival = value;
    }

    /**
     * Gets the value of the rtTimeAtArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtTimeAtArrival() {
        return rtTimeAtArrival;
    }

    /**
     * Sets the value of the rtTimeAtArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtTimeAtArrival(String value) {
        this.rtTimeAtArrival = value;
    }

    /**
     * Gets the value of the rtDateAtArrival property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRtDateAtArrival() {
        return rtDateAtArrival;
    }

    /**
     * Sets the value of the rtDateAtArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRtDateAtArrival(String value) {
        this.rtDateAtArrival = value;
    }

    /**
     * Gets the value of the trainNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainNumber() {
        return trainNumber;
    }

    /**
     * Sets the value of the trainNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainNumber(String value) {
        this.trainNumber = value;
    }

    /**
     * Gets the value of the trainCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrainCategory() {
        return trainCategory;
    }

    /**
     * Sets the value of the trainCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrainCategory(String value) {
        this.trainCategory = value;
    }

    /**
     * Gets the value of the isFastest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFastest() {
        return isFastest;
    }

    /**
     * Sets the value of the isFastest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFastest(Boolean value) {
        this.isFastest = value;
    }

}
