//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EcoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EcoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="co2" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *       &lt;attribute name="part" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *       &lt;attribute name="partV" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *       &lt;attribute name="nmhc" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *       &lt;attribute name="nox" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *       &lt;attribute name="prime" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *       &lt;attribute name="so2" type="{http://www.w3.org/2001/XMLSchema}double" default="0.0" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EcoType")
public class EcoType {

    @XmlAttribute(name = "co2")
    protected Double co2;
    @XmlAttribute(name = "part")
    protected Double part;
    @XmlAttribute(name = "partV")
    protected Double partV;
    @XmlAttribute(name = "nmhc")
    protected Double nmhc;
    @XmlAttribute(name = "nox")
    protected Double nox;
    @XmlAttribute(name = "prime")
    protected Double prime;
    @XmlAttribute(name = "so2")
    protected Double so2;

    /**
     * Gets the value of the co2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getCo2() {
        if (co2 == null) {
            return  0.0D;
        } else {
            return co2;
        }
    }

    /**
     * Sets the value of the co2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCo2(Double value) {
        this.co2 = value;
    }

    /**
     * Gets the value of the part property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPart() {
        if (part == null) {
            return  0.0D;
        } else {
            return part;
        }
    }

    /**
     * Sets the value of the part property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPart(Double value) {
        this.part = value;
    }

    /**
     * Gets the value of the partV property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPartV() {
        if (partV == null) {
            return  0.0D;
        } else {
            return partV;
        }
    }

    /**
     * Sets the value of the partV property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPartV(Double value) {
        this.partV = value;
    }

    /**
     * Gets the value of the nmhc property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getNmhc() {
        if (nmhc == null) {
            return  0.0D;
        } else {
            return nmhc;
        }
    }

    /**
     * Sets the value of the nmhc property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNmhc(Double value) {
        this.nmhc = value;
    }

    /**
     * Gets the value of the nox property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getNox() {
        if (nox == null) {
            return  0.0D;
        } else {
            return nox;
        }
    }

    /**
     * Sets the value of the nox property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setNox(Double value) {
        this.nox = value;
    }

    /**
     * Gets the value of the prime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getPrime() {
        if (prime == null) {
            return  0.0D;
        } else {
            return prime;
        }
    }

    /**
     * Sets the value of the prime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPrime(Double value) {
        this.prime = value;
    }

    /**
     * Gets the value of the so2 property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public double getSo2() {
        if (so2 == null) {
            return  0.0D;
        } else {
            return so2;
        }
    }

    /**
     * Sets the value of the so2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSo2(Double value) {
        this.so2 = value;
    }

}
