//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GisRouteRoadType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GisRouteRoadType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="M"/>
 *     &lt;enumeration value="H"/>
 *     &lt;enumeration value="T"/>
 *     &lt;enumeration value="T4L"/>
 *     &lt;enumeration value="T2L"/>
 *     &lt;enumeration value="TR"/>
 *     &lt;enumeration value="NT"/>
 *     &lt;enumeration value="CT"/>
 *     &lt;enumeration value="R"/>
 *     &lt;enumeration value="B"/>
 *     &lt;enumeration value="CW"/>
 *     &lt;enumeration value="C"/>
 *     &lt;enumeration value="W"/>
 *     &lt;enumeration value="F"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GisRouteRoadType")
@XmlEnum
public enum GisRouteRoadType {


    /**
     * Unknown
     * 
     */
    U("U"),

    /**
     * Motorway
     * 
     */
    M("M"),

    /**
     * Highway
     * 
     */
    H("H"),

    /**
     * Trunk road
     * 
     */
    T("T"),

    /**
     * Trunk road with four lanes
     * 
     */
    @XmlEnumValue("T4L")
    T_4_L("T4L"),

    /**
     * Trunk road with two lanes
     * 
     */
    @XmlEnumValue("T2L")
    T_2_L("T2L"),

    /**
     * Country road
     * 
     */
    TR("TR"),

    /**
     * County road
     * 
     */
    NT("NT"),

    /**
     * City road
     * 
     */
    CT("CT"),

    /**
     * Residential road
     * 
     */
    R("R"),

    /**
     * Blocked road
     * 
     */
    B("B"),

    /**
     * Combined cycle and walkway
     * 
     */
    CW("CW"),

    /**
     * Cycleway
     * 
     */
    C("C"),

    /**
     * Walkway
     * 
     */
    W("W"),

    /**
     * Ferry
     * 
     */
    F("F");
    private final String value;

    GisRouteRoadType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static GisRouteRoadType fromValue(String v) {
        for (GisRouteRoadType c: GisRouteRoadType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
