//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GisRouteSegment complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GisRouteSegment">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{hafas_rest}Notes" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="rType" type="{hafas_rest}GisRouteRoadType" />
 *       &lt;attribute name="rNum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="man" type="{hafas_rest}GisRouteManoeuvre" />
 *       &lt;attribute name="manTx" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="dirTx" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ori" type="{hafas_rest}GisRouteOrientation" />
 *       &lt;attribute name="polyS" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="polyE" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="dist" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GisRouteSegment", propOrder = {
    "notes"
})
public class GisRouteSegment {

    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "rType")
    protected GisRouteRoadType rType;
    @XmlAttribute(name = "rNum")
    protected String rNum;
    @XmlAttribute(name = "man")
    protected GisRouteManoeuvre man;
    @XmlAttribute(name = "manTx")
    protected String manTx;
    @XmlAttribute(name = "dirTx")
    protected String dirTx;
    @XmlAttribute(name = "ori")
    protected GisRouteOrientation ori;
    @XmlAttribute(name = "polyS")
    protected Integer polyS;
    @XmlAttribute(name = "polyE")
    protected Integer polyE;
    @XmlAttribute(name = "dist")
    protected Integer dist;

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the rType property.
     * 
     * @return
     *     possible object is
     *     {@link GisRouteRoadType }
     *     
     */
    public GisRouteRoadType getRType() {
        return rType;
    }

    /**
     * Sets the value of the rType property.
     * 
     * @param value
     *     allowed object is
     *     {@link GisRouteRoadType }
     *     
     */
    public void setRType(GisRouteRoadType value) {
        this.rType = value;
    }

    /**
     * Gets the value of the rNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRNum() {
        return rNum;
    }

    /**
     * Sets the value of the rNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRNum(String value) {
        this.rNum = value;
    }

    /**
     * Gets the value of the man property.
     * 
     * @return
     *     possible object is
     *     {@link GisRouteManoeuvre }
     *     
     */
    public GisRouteManoeuvre getMan() {
        return man;
    }

    /**
     * Sets the value of the man property.
     * 
     * @param value
     *     allowed object is
     *     {@link GisRouteManoeuvre }
     *     
     */
    public void setMan(GisRouteManoeuvre value) {
        this.man = value;
    }

    /**
     * Gets the value of the manTx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getManTx() {
        return manTx;
    }

    /**
     * Sets the value of the manTx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setManTx(String value) {
        this.manTx = value;
    }

    /**
     * Gets the value of the dirTx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirTx() {
        return dirTx;
    }

    /**
     * Sets the value of the dirTx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirTx(String value) {
        this.dirTx = value;
    }

    /**
     * Gets the value of the ori property.
     * 
     * @return
     *     possible object is
     *     {@link GisRouteOrientation }
     *     
     */
    public GisRouteOrientation getOri() {
        return ori;
    }

    /**
     * Sets the value of the ori property.
     * 
     * @param value
     *     allowed object is
     *     {@link GisRouteOrientation }
     *     
     */
    public void setOri(GisRouteOrientation value) {
        this.ori = value;
    }

    /**
     * Gets the value of the polyS property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPolyS() {
        return polyS;
    }

    /**
     * Sets the value of the polyS property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPolyS(Integer value) {
        this.polyS = value;
    }

    /**
     * Gets the value of the polyE property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPolyE() {
        return polyE;
    }

    /**
     * Sets the value of the polyE property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPolyE(Integer value) {
        this.polyE = value;
    }

    /**
     * Gets the value of the dist property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDist() {
        return dist;
    }

    /**
     * Sets the value of the dist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDist(Integer value) {
        this.dist = value;
    }

}
