//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GisRouteOrientation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="GisRouteOrientation">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="U"/>
 *     &lt;enumeration value="N"/>
 *     &lt;enumeration value="S"/>
 *     &lt;enumeration value="E"/>
 *     &lt;enumeration value="W"/>
 *     &lt;enumeration value="NE"/>
 *     &lt;enumeration value="SE"/>
 *     &lt;enumeration value="NW"/>
 *     &lt;enumeration value="SW"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "GisRouteOrientation")
@XmlEnum
public enum GisRouteOrientation {


    /**
     * Unknown
     * 
     */
    U,

    /**
     * North
     * 
     */
    N,

    /**
     * South
     * 
     */
    S,

    /**
     * East
     * 
     */
    E,

    /**
     * West
     * 
     */
    W,

    /**
     * Northeast
     * 
     */
    NE,

    /**
     * Southeast
     * 
     */
    SE,

    /**
     * Northwest
     * 
     */
    NW,

    /**
     * Southwest
     * 
     */
    SW;

    public String value() {
        return name();
    }

    public static GisRouteOrientation fromValue(String v) {
        return valueOf(v);
    }

}
