//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import com.devtty.neb27k.jaxb.GisRouteType;
import com.devtty.neb27k.jaxb.GisRef;
import com.devtty.neb27k.jaxb.GeometryRef;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{hafas_rest}Origin"/>
 *         &lt;element ref="{hafas_rest}Destination"/>
 *         &lt;element ref="{hafas_rest}Notes" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}JourneyDetailRef" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}GeometryRef" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}GisRef" minOccurs="0"/>
 *         &lt;element name="GisRoute" type="{hafas_rest}GisRouteType" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}Messages" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}JourneyStatus" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}Product" minOccurs="0"/>
 *         &lt;element name="Polyline" type="{hafas_rest}Polyline" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}Stops" minOccurs="0"/>
 *         &lt;element ref="{hafas_rest}ServiceDays" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{hafas_rest}attlist.Leg"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "origin",
    "destination",
    "notes",
    "journeyDetailRef",
    "geometryRef",
    "gisRef",
    "gisRoute",
    "messages",
    "journeyStatus",
    "product",
    "polyline",
    "stops",
    "serviceDays"
})
@XmlRootElement(name = "Leg")
public class Leg {

    @XmlElement(name = "Origin", required = true)
    protected OriginDestType origin;
    @XmlElement(name = "Destination", required = true)
    protected OriginDestType destination;
    @XmlElement(name = "Notes")
    protected Notes notes;
    @XmlElement(name = "JourneyDetailRef")
    protected JourneyDetailRef journeyDetailRef;
    @XmlElement(name = "GeometryRef")
    protected GeometryRef geometryRef;
    @XmlElement(name = "GisRef")
    protected GisRef gisRef;
    @XmlElement(name = "GisRoute")
    protected GisRouteType gisRoute;
    @XmlElement(name = "Messages")
    protected Messages messages;
    @XmlElement(name = "JourneyStatus")
    protected String journeyStatus;
    @XmlElement(name = "Product")
    protected Product product;
    @XmlElement(name = "Polyline")
    protected Polyline polyline;
    @XmlElement(name = "Stops")
    protected Stops stops;
    @XmlElement(name = "ServiceDays")
    protected List<ServiceDays> serviceDays;
    @XmlAttribute(name = "idx", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String idx;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "number")
    protected String number;
    @XmlAttribute(name = "category")
    protected String category;
    @XmlAttribute(name = "type", required = true)
    protected String type;
    @XmlAttribute(name = "cancelled")
    protected Boolean cancelled;
    @XmlAttribute(name = "reachable")
    protected Boolean reachable;
    @XmlAttribute(name = "direction")
    protected String direction;
    @XmlAttribute(name = "duration")
    protected Duration duration;
    @XmlAttribute(name = "dist")
    protected Integer dist;

    /**
     * Gets the value of the origin property.
     * 
     * @return
     *     possible object is
     *     {@link OriginDestType }
     *     
     */
    public OriginDestType getOrigin() {
        return origin;
    }

    /**
     * Sets the value of the origin property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginDestType }
     *     
     */
    public void setOrigin(OriginDestType value) {
        this.origin = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link OriginDestType }
     *     
     */
    public OriginDestType getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link OriginDestType }
     *     
     */
    public void setDestination(OriginDestType value) {
        this.destination = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the journeyDetailRef property.
     * 
     * @return
     *     possible object is
     *     {@link JourneyDetailRef }
     *     
     */
    public JourneyDetailRef getJourneyDetailRef() {
        return journeyDetailRef;
    }

    /**
     * Sets the value of the journeyDetailRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link JourneyDetailRef }
     *     
     */
    public void setJourneyDetailRef(JourneyDetailRef value) {
        this.journeyDetailRef = value;
    }

    /**
     * Gets the value of the geometryRef property.
     * 
     * @return
     *     possible object is
     *     {@link GeometryRef }
     *     
     */
    public GeometryRef getGeometryRef() {
        return geometryRef;
    }

    /**
     * Sets the value of the geometryRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeometryRef }
     *     
     */
    public void setGeometryRef(GeometryRef value) {
        this.geometryRef = value;
    }

    /**
     * Gets the value of the gisRef property.
     * 
     * @return
     *     possible object is
     *     {@link GisRef }
     *     
     */
    public GisRef getGisRef() {
        return gisRef;
    }

    /**
     * Sets the value of the gisRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link GisRef }
     *     
     */
    public void setGisRef(GisRef value) {
        this.gisRef = value;
    }

    /**
     * Gets the value of the gisRoute property.
     * 
     * @return
     *     possible object is
     *     {@link GisRouteType }
     *     
     */
    public GisRouteType getGisRoute() {
        return gisRoute;
    }

    /**
     * Sets the value of the gisRoute property.
     * 
     * @param value
     *     allowed object is
     *     {@link GisRouteType }
     *     
     */
    public void setGisRoute(GisRouteType value) {
        this.gisRoute = value;
    }

    /**
     * Gets the value of the messages property.
     * 
     * @return
     *     possible object is
     *     {@link Messages }
     *     
     */
    public Messages getMessages() {
        return messages;
    }

    /**
     * Sets the value of the messages property.
     * 
     * @param value
     *     allowed object is
     *     {@link Messages }
     *     
     */
    public void setMessages(Messages value) {
        this.messages = value;
    }

    /**
     * Gets the value of the journeyStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJourneyStatus() {
        return journeyStatus;
    }

    /**
     * Sets the value of the journeyStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJourneyStatus(String value) {
        this.journeyStatus = value;
    }

    /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link Product }
     *     
     */
    public Product getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link Product }
     *     
     */
    public void setProduct(Product value) {
        this.product = value;
    }

    /**
     * Gets the value of the polyline property.
     * 
     * @return
     *     possible object is
     *     {@link Polyline }
     *     
     */
    public Polyline getPolyline() {
        return polyline;
    }

    /**
     * Sets the value of the polyline property.
     * 
     * @param value
     *     allowed object is
     *     {@link Polyline }
     *     
     */
    public void setPolyline(Polyline value) {
        this.polyline = value;
    }

    /**
     * Gets the value of the stops property.
     * 
     * @return
     *     possible object is
     *     {@link Stops }
     *     
     */
    public Stops getStops() {
        return stops;
    }

    /**
     * Sets the value of the stops property.
     * 
     * @param value
     *     allowed object is
     *     {@link Stops }
     *     
     */
    public void setStops(Stops value) {
        this.stops = value;
    }

    /**
     * Gets the value of the serviceDays property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the serviceDays property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getServiceDays().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ServiceDays }
     * 
     * 
     */
    public List<ServiceDays> getServiceDays() {
        if (serviceDays == null) {
            serviceDays = new ArrayList<ServiceDays>();
        }
        return this.serviceDays;
    }

    /**
     * Gets the value of the idx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdx() {
        return idx;
    }

    /**
     * Sets the value of the idx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdx(String value) {
        this.idx = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCategory(String value) {
        this.category = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the cancelled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCancelled() {
        if (cancelled == null) {
            return false;
        } else {
            return cancelled;
        }
    }

    /**
     * Sets the value of the cancelled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCancelled(Boolean value) {
        this.cancelled = value;
    }

    /**
     * Gets the value of the reachable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReachable() {
        if (reachable == null) {
            return true;
        } else {
            return reachable;
        }
    }

    /**
     * Sets the value of the reachable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReachable(Boolean value) {
        this.reachable = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirection(String value) {
        this.direction = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setDuration(Duration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the dist property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDist() {
        return dist;
    }

    /**
     * Sets the value of the dist property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDist(Integer value) {
        this.dist = value;
    }

}
