//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for messageType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="messageType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="UNDEF"/>
 *     &lt;enumeration value="JNY"/>
 *     &lt;enumeration value="ROU"/>
 *     &lt;enumeration value="LIN"/>
 *     &lt;enumeration value="REG"/>
 *     &lt;enumeration value="CNTY"/>
 *     &lt;enumeration value="GLOB"/>
 *     &lt;enumeration value="LOC"/>
 *     &lt;enumeration value="FOOT"/>
 *     &lt;enumeration value="HEAD"/>
 *     &lt;enumeration value="PSGR"/>
 *     &lt;enumeration value="IFRA"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "messageType")
@XmlEnum
public enum MessageType {

    UNDEF,
    JNY,
    ROU,
    LIN,
    REG,
    CNTY,
    GLOB,
    LOC,
    FOOT,
    HEAD,
    PSGR,
    IFRA;

    public String value() {
        return name();
    }

    public static MessageType fromValue(String v) {
        return valueOf(v);
    }

}
