//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="num" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="line" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="catOut" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="catIn" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="catCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="catOutS" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="catOutL" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operatorCode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="operator" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="admin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "Product")
public class Product {

    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "num")
    protected String num;
    @XmlAttribute(name = "line")
    protected String line;
    @XmlAttribute(name = "catOut")
    protected String catOut;
    @XmlAttribute(name = "catIn")
    protected String catIn;
    @XmlAttribute(name = "catCode")
    protected String catCode;
    @XmlAttribute(name = "catOutS")
    protected String catOutS;
    @XmlAttribute(name = "catOutL")
    protected String catOutL;
    @XmlAttribute(name = "operatorCode")
    protected String operatorCode;
    @XmlAttribute(name = "operator")
    protected String operator;
    @XmlAttribute(name = "admin")
    protected String admin;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the num property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNum() {
        return num;
    }

    /**
     * Sets the value of the num property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNum(String value) {
        this.num = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the catOut property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatOut() {
        return catOut;
    }

    /**
     * Sets the value of the catOut property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatOut(String value) {
        this.catOut = value;
    }

    /**
     * Gets the value of the catIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatIn() {
        return catIn;
    }

    /**
     * Sets the value of the catIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatIn(String value) {
        this.catIn = value;
    }

    /**
     * Gets the value of the catCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatCode() {
        return catCode;
    }

    /**
     * Sets the value of the catCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatCode(String value) {
        this.catCode = value;
    }

    /**
     * Gets the value of the catOutS property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatOutS() {
        return catOutS;
    }

    /**
     * Sets the value of the catOutS property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatOutS(String value) {
        this.catOutS = value;
    }

    /**
     * Gets the value of the catOutL property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCatOutL() {
        return catOutL;
    }

    /**
     * Sets the value of the catOutL property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCatOutL(String value) {
        this.catOutL = value;
    }

    /**
     * Gets the value of the operatorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorCode() {
        return operatorCode;
    }

    /**
     * Sets the value of the operatorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorCode(String value) {
        this.operatorCode = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the admin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmin() {
        return admin;
    }

    /**
     * Sets the value of the admin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmin(String value) {
        this.admin = value;
    }

}
