//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Irregular service days for this trip meaning the days there this train runs on a different schedule.
 * 
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="planningPeriodBegin" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="planningPeriodEnd" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sDaysR" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sDaysI" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="sDaysB" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="routeIdxFrom" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="routeIdxTo" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "")
@XmlRootElement(name = "ServiceDays")
public class ServiceDays {

    @XmlAttribute(name = "planningPeriodBegin")
    protected String planningPeriodBegin;
    @XmlAttribute(name = "planningPeriodEnd")
    protected String planningPeriodEnd;
    @XmlAttribute(name = "sDaysR")
    protected String sDaysR;
    @XmlAttribute(name = "sDaysI")
    protected String sDaysI;
    @XmlAttribute(name = "sDaysB")
    protected String sDaysB;
    @XmlAttribute(name = "routeIdxFrom")
    protected Integer routeIdxFrom;
    @XmlAttribute(name = "routeIdxTo")
    protected Integer routeIdxTo;

    /**
     * Gets the value of the planningPeriodBegin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanningPeriodBegin() {
        return planningPeriodBegin;
    }

    /**
     * Sets the value of the planningPeriodBegin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanningPeriodBegin(String value) {
        this.planningPeriodBegin = value;
    }

    /**
     * Gets the value of the planningPeriodEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlanningPeriodEnd() {
        return planningPeriodEnd;
    }

    /**
     * Sets the value of the planningPeriodEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlanningPeriodEnd(String value) {
        this.planningPeriodEnd = value;
    }

    /**
     * Gets the value of the sDaysR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDaysR() {
        return sDaysR;
    }

    /**
     * Sets the value of the sDaysR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDaysR(String value) {
        this.sDaysR = value;
    }

    /**
     * Gets the value of the sDaysI property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDaysI() {
        return sDaysI;
    }

    /**
     * Sets the value of the sDaysI property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDaysI(String value) {
        this.sDaysI = value;
    }

    /**
     * Gets the value of the sDaysB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSDaysB() {
        return sDaysB;
    }

    /**
     * Sets the value of the sDaysB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSDaysB(String value) {
        this.sDaysB = value;
    }

    /**
     * Gets the value of the routeIdxFrom property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRouteIdxFrom() {
        return routeIdxFrom;
    }

    /**
     * Sets the value of the routeIdxFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRouteIdxFrom(Integer value) {
        this.routeIdxFrom = value;
    }

    /**
     * Gets the value of the routeIdxTo property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRouteIdxTo() {
        return routeIdxTo;
    }

    /**
     * Sets the value of the routeIdxTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRouteIdxTo(Integer value) {
        this.routeIdxTo = value;
    }

}
