//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Stop" maxOccurs="unbounded" minOccurs="2">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element ref="{hafas_rest}Notes" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attGroup ref="{hafas_rest}attlist.Stop"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stop"
})
@XmlRootElement(name = "Stops")
public class Stops {

    @XmlElement(name = "Stop", required = true)
    protected List<Stops.Stop> stop;

    /**
     * Gets the value of the stop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Stops.Stop }
     * 
     * 
     */
    public List<Stops.Stop> getStop() {
        if (stop == null) {
            stop = new ArrayList<Stops.Stop>();
        }
        return this.stop;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element ref="{hafas_rest}Notes" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attGroup ref="{hafas_rest}attlist.Stop"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "notes"
    })
    public static class Stop {

        @XmlElement(name = "Notes")
        protected Notes notes;
        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "id", required = true)
        protected String id;
        @XmlAttribute(name = "extId", required = true)
        protected String extId;
        @XmlAttribute(name = "routeIdx")
        protected Integer routeIdx;
        @XmlAttribute(name = "lon")
        protected BigDecimal lon;
        @XmlAttribute(name = "lat")
        protected BigDecimal lat;
        @XmlAttribute(name = "arrPrognosisType")
        protected PrognosisType arrPrognosisType;
        @XmlAttribute(name = "depPrognosisType")
        protected PrognosisType depPrognosisType;
        @XmlAttribute(name = "depTime")
        protected String depTime;
        @XmlAttribute(name = "depDate")
        protected String depDate;
        @XmlAttribute(name = "depTz")
        protected Integer depTz;
        @XmlAttribute(name = "arrTime")
        protected String arrTime;
        @XmlAttribute(name = "arrDate")
        protected String arrDate;
        @XmlAttribute(name = "arrTz")
        protected Integer arrTz;
        @XmlAttribute(name = "passingTime")
        protected String passingTime;
        @XmlAttribute(name = "passingDate")
        protected String passingDate;
        @XmlAttribute(name = "passingTz")
        protected Integer passingTz;
        @XmlAttribute(name = "arrTrack")
        protected String arrTrack;
        @XmlAttribute(name = "depTrack")
        protected String depTrack;
        @XmlAttribute(name = "rtDepTime")
        protected String rtDepTime;
        @XmlAttribute(name = "rtDepDate")
        protected String rtDepDate;
        @XmlAttribute(name = "rtDepTz")
        protected Integer rtDepTz;
        @XmlAttribute(name = "rtArrTime")
        protected String rtArrTime;
        @XmlAttribute(name = "rtArrDate")
        protected String rtArrDate;
        @XmlAttribute(name = "rtArrTz")
        protected Integer rtArrTz;
        @XmlAttribute(name = "rtArrTrack")
        protected String rtArrTrack;
        @XmlAttribute(name = "rtDepTrack")
        protected String rtDepTrack;
        @XmlAttribute(name = "rtPassingTime")
        protected String rtPassingTime;
        @XmlAttribute(name = "rtPassingDate")
        protected String rtPassingDate;
        @XmlAttribute(name = "rtPassingTz")
        protected Integer rtPassingTz;
        @XmlAttribute(name = "cancelled")
        protected Boolean cancelled;

        /**
         * Contains a list of notes to be displayed for this location, like attributes or footnotes.
         * 
         * @return
         *     possible object is
         *     {@link Notes }
         *     
         */
        public Notes getNotes() {
            return notes;
        }

        /**
         * Sets the value of the notes property.
         * 
         * @param value
         *     allowed object is
         *     {@link Notes }
         *     
         */
        public void setNotes(Notes value) {
            this.notes = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the extId property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExtId() {
            return extId;
        }

        /**
         * Sets the value of the extId property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExtId(String value) {
            this.extId = value;
        }

        /**
         * Gets the value of the routeIdx property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getRouteIdx() {
            return routeIdx;
        }

        /**
         * Sets the value of the routeIdx property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRouteIdx(Integer value) {
            this.routeIdx = value;
        }

        /**
         * Gets the value of the lon property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLon() {
            return lon;
        }

        /**
         * Sets the value of the lon property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLon(BigDecimal value) {
            this.lon = value;
        }

        /**
         * Gets the value of the lat property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getLat() {
            return lat;
        }

        /**
         * Sets the value of the lat property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setLat(BigDecimal value) {
            this.lat = value;
        }

        /**
         * Gets the value of the arrPrognosisType property.
         * 
         * @return
         *     possible object is
         *     {@link PrognosisType }
         *     
         */
        public PrognosisType getArrPrognosisType() {
            return arrPrognosisType;
        }

        /**
         * Sets the value of the arrPrognosisType property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrognosisType }
         *     
         */
        public void setArrPrognosisType(PrognosisType value) {
            this.arrPrognosisType = value;
        }

        /**
         * Gets the value of the depPrognosisType property.
         * 
         * @return
         *     possible object is
         *     {@link PrognosisType }
         *     
         */
        public PrognosisType getDepPrognosisType() {
            return depPrognosisType;
        }

        /**
         * Sets the value of the depPrognosisType property.
         * 
         * @param value
         *     allowed object is
         *     {@link PrognosisType }
         *     
         */
        public void setDepPrognosisType(PrognosisType value) {
            this.depPrognosisType = value;
        }

        /**
         * Gets the value of the depTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepTime() {
            return depTime;
        }

        /**
         * Sets the value of the depTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepTime(String value) {
            this.depTime = value;
        }

        /**
         * Gets the value of the depDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepDate() {
            return depDate;
        }

        /**
         * Sets the value of the depDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepDate(String value) {
            this.depDate = value;
        }

        /**
         * Gets the value of the depTz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getDepTz() {
            if (depTz == null) {
                return  0;
            } else {
                return depTz;
            }
        }

        /**
         * Sets the value of the depTz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setDepTz(Integer value) {
            this.depTz = value;
        }

        /**
         * Gets the value of the arrTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrTime() {
            return arrTime;
        }

        /**
         * Sets the value of the arrTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrTime(String value) {
            this.arrTime = value;
        }

        /**
         * Gets the value of the arrDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrDate() {
            return arrDate;
        }

        /**
         * Sets the value of the arrDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrDate(String value) {
            this.arrDate = value;
        }

        /**
         * Gets the value of the arrTz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getArrTz() {
            if (arrTz == null) {
                return  0;
            } else {
                return arrTz;
            }
        }

        /**
         * Sets the value of the arrTz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setArrTz(Integer value) {
            this.arrTz = value;
        }

        /**
         * Gets the value of the passingTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassingTime() {
            return passingTime;
        }

        /**
         * Sets the value of the passingTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassingTime(String value) {
            this.passingTime = value;
        }

        /**
         * Gets the value of the passingDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPassingDate() {
            return passingDate;
        }

        /**
         * Sets the value of the passingDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPassingDate(String value) {
            this.passingDate = value;
        }

        /**
         * Gets the value of the passingTz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getPassingTz() {
            if (passingTz == null) {
                return  0;
            } else {
                return passingTz;
            }
        }

        /**
         * Sets the value of the passingTz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setPassingTz(Integer value) {
            this.passingTz = value;
        }

        /**
         * Gets the value of the arrTrack property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getArrTrack() {
            return arrTrack;
        }

        /**
         * Sets the value of the arrTrack property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setArrTrack(String value) {
            this.arrTrack = value;
        }

        /**
         * Gets the value of the depTrack property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDepTrack() {
            return depTrack;
        }

        /**
         * Sets the value of the depTrack property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDepTrack(String value) {
            this.depTrack = value;
        }

        /**
         * Gets the value of the rtDepTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtDepTime() {
            return rtDepTime;
        }

        /**
         * Sets the value of the rtDepTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtDepTime(String value) {
            this.rtDepTime = value;
        }

        /**
         * Gets the value of the rtDepDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtDepDate() {
            return rtDepDate;
        }

        /**
         * Sets the value of the rtDepDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtDepDate(String value) {
            this.rtDepDate = value;
        }

        /**
         * Gets the value of the rtDepTz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getRtDepTz() {
            if (rtDepTz == null) {
                return  0;
            } else {
                return rtDepTz;
            }
        }

        /**
         * Sets the value of the rtDepTz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRtDepTz(Integer value) {
            this.rtDepTz = value;
        }

        /**
         * Gets the value of the rtArrTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtArrTime() {
            return rtArrTime;
        }

        /**
         * Sets the value of the rtArrTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtArrTime(String value) {
            this.rtArrTime = value;
        }

        /**
         * Gets the value of the rtArrDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtArrDate() {
            return rtArrDate;
        }

        /**
         * Sets the value of the rtArrDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtArrDate(String value) {
            this.rtArrDate = value;
        }

        /**
         * Gets the value of the rtArrTz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getRtArrTz() {
            if (rtArrTz == null) {
                return  0;
            } else {
                return rtArrTz;
            }
        }

        /**
         * Sets the value of the rtArrTz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRtArrTz(Integer value) {
            this.rtArrTz = value;
        }

        /**
         * Gets the value of the rtArrTrack property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtArrTrack() {
            return rtArrTrack;
        }

        /**
         * Sets the value of the rtArrTrack property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtArrTrack(String value) {
            this.rtArrTrack = value;
        }

        /**
         * Gets the value of the rtDepTrack property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtDepTrack() {
            return rtDepTrack;
        }

        /**
         * Sets the value of the rtDepTrack property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtDepTrack(String value) {
            this.rtDepTrack = value;
        }

        /**
         * Gets the value of the rtPassingTime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtPassingTime() {
            return rtPassingTime;
        }

        /**
         * Sets the value of the rtPassingTime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtPassingTime(String value) {
            this.rtPassingTime = value;
        }

        /**
         * Gets the value of the rtPassingDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRtPassingDate() {
            return rtPassingDate;
        }

        /**
         * Sets the value of the rtPassingDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRtPassingDate(String value) {
            this.rtPassingDate = value;
        }

        /**
         * Gets the value of the rtPassingTz property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public int getRtPassingTz() {
            if (rtPassingTz == null) {
                return  0;
            } else {
                return rtPassingTz;
            }
        }

        /**
         * Sets the value of the rtPassingTz property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRtPassingTz(Integer value) {
            this.rtPassingTz = value;
        }

        /**
         * Gets the value of the cancelled property.
         * 
         * @return
         *     possible object is
         *     {@link Boolean }
         *     
         */
        public boolean isCancelled() {
            if (cancelled == null) {
                return false;
            } else {
                return cancelled;
            }
        }

        /**
         * Sets the value of the cancelled property.
         * 
         * @param value
         *     allowed object is
         *     {@link Boolean }
         *     
         */
        public void setCancelled(Boolean value) {
            this.cancelled = value;
        }

    }

}
