//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.04 at 02:33:07 PM CEST 
//


package com.devtty.neb27k.jaxb;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{hafas_rest}Trip" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Pricing" type="{hafas_rest}pricingType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{hafas_rest}attlist.TripList"/>
 *       &lt;attGroup ref="{hafas_rest}attlist.Common"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "trip",
    "pricing"
})
@XmlRootElement(name = "TripList")
public class TripList {

    @XmlElement(name = "Trip")
    protected List<Trip> trip;
    @XmlElement(name = "Pricing")
    protected List<PricingType> pricing;
    @XmlAttribute(name = "scrB")
    protected String scrB;
    @XmlAttribute(name = "scrF")
    protected String scrF;
    @XmlAttribute(name = "scrReturnB")
    protected String scrReturnB;
    @XmlAttribute(name = "scrReturnF")
    protected String scrReturnF;
    @XmlAttribute(name = "serverVersion")
    protected String serverVersion;
    @XmlAttribute(name = "dialectVersion")
    protected String dialectVersion;
    @XmlAttribute(name = "version")
    protected String version;
    @XmlAttribute(name = "errorCode")
    protected String errorCode;
    @XmlAttribute(name = "errorText")
    protected String errorText;

    /**
     * Gets the value of the trip property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the trip property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTrip().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Trip }
     * 
     * 
     */
    public List<Trip> getTrip() {
        if (trip == null) {
            trip = new ArrayList<Trip>();
        }
        return this.trip;
    }

    /**
     * Gets the value of the pricing property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pricing property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPricing().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PricingType }
     * 
     * 
     */
    public List<PricingType> getPricing() {
        if (pricing == null) {
            pricing = new ArrayList<PricingType>();
        }
        return this.pricing;
    }

    /**
     * Gets the value of the scrB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrB() {
        return scrB;
    }

    /**
     * Sets the value of the scrB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrB(String value) {
        this.scrB = value;
    }

    /**
     * Gets the value of the scrF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrF() {
        return scrF;
    }

    /**
     * Sets the value of the scrF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrF(String value) {
        this.scrF = value;
    }

    /**
     * Gets the value of the scrReturnB property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrReturnB() {
        return scrReturnB;
    }

    /**
     * Sets the value of the scrReturnB property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrReturnB(String value) {
        this.scrReturnB = value;
    }

    /**
     * Gets the value of the scrReturnF property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScrReturnF() {
        return scrReturnF;
    }

    /**
     * Sets the value of the scrReturnF property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScrReturnF(String value) {
        this.scrReturnF = value;
    }

    /**
     * Gets the value of the serverVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getServerVersion() {
        return serverVersion;
    }

    /**
     * Sets the value of the serverVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerVersion(String value) {
        this.serverVersion = value;
    }

    /**
     * Gets the value of the dialectVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDialectVersion() {
        return dialectVersion;
    }

    /**
     * Sets the value of the dialectVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDialectVersion(String value) {
        this.dialectVersion = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the errorCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorCode() {
        return errorCode;
    }

    /**
     * Sets the value of the errorCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorCode(String value) {
        this.errorCode = value;
    }

    /**
     * Gets the value of the errorText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorText() {
        return errorText;
    }

    /**
     * Sets the value of the errorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorText(String value) {
        this.errorText = value;
    }

}
